FileExchange/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('mainapp.urls')),
	# (r'^$', RedirectView.as_view(url='/myapp/list/')),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^movie/$', 'movie.views.movie_list'),
    url(r'^movie/(\d+)/$', 'movie.views.movie'),
    url(r'^movie/(\d+)/add/$', 'movie.views.buy'),
    url(r'^movie/thanks/$', 'movie.views.thanks'),
    url(r'^$', 'core.views.index_page'),
    url(r'^login/$', 'simpleauth.views.login'),
    url(r'^registration/$', 'simpleauth.views.registration'),
    url(r'^logout/$', 'simpleauth.views.logout'),
    url(r'^account/$', 'simpleauth.views.account'),
    url(r'^account/edit/$', 'simpleauth.views.account_edit'),
    url(r'^pay/$', 'movie.views.paypage'),
    url(r'^paying/$', 'movie.views.pay')
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
)

django_tasks/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('forum.urls', namespace='forum')),
)

forum/urls.py
from django.conf.urls import patterns, url

from forum import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name = 'index'),
                       url(r'^(?P<page_num>\d+)$', views.IndexView.as_view(), name='index_page'),
                       url(r'^theme/(?P<pk>\d+)$', views.DetailsView.as_view(), name = 'theme_mess'),
                       url(r'^theme/(?P<pk>\d+)/add_message$', views.add_message, name = 'add_message'),
                       url(r'^login$', views.LoginView.as_view(), name = 'login_page'),
                       url(r'^logout$', views.logout_view, name = 'logout'),
                       url(r'^register$', views.RegisterView.as_view(), name = 'register'),
                       url(r'^add_theme$', views.add_theme, name = 'add_theme'),
                       url(r'^theme/(?P<tpk>\d+)/delete_mess/(?P<mpk>\d+)', views.delete_message, name = 'delete_mess'),
                       url(r'^theme/(?P<tpk>\d+)/edit_mess/(?P<mpk>\d+)', views.edit_mess_page, name = 'edit_mess'),
                       )

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('audios.urls')),
)

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

forum/models.py
from django.db import models
from django.contrib.auth.models import User

class Theme(models.Model):
    name = models.CharField(max_length = 100)
    created = models.DateTimeField()
    author = models.ForeignKey(User)
    def __unicode__(self):
        if len(self.name) > 10:
            return self.name[0:10] + '...'
        return self.name

class Message(models.Model):
    theme = models.ForeignKey(Theme)
    text = models.CharField(max_length = 1000)
    created = models.DateTimeField()
    author = models.ForeignKey(User)
    def __unicode__(self):
        if len(self.theme.name) > 10:
            theme = self.theme.name[0:10] + '...'
        else:
            theme = self.theme.name
        if len(self.text) > 10:
            text = self.text[0:10] + '...'
        else:
            text = self.text
        return self.author.username + ' | ' + theme + ' | ' + text

forum/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=30, widget=forms.TextInput, required=True)
    password = forms.CharField(max_length=40, widget=forms.PasswordInput, required=True)


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1','password2')


class EditForm(forms.Form):
    message = forms.CharField(max_length=1000, widget=forms.Textarea)

forum/views.py
from django.shortcuts import render, get_object_or_404
from forum.models import Theme, Message
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.views import generic
from forum.forms import LoginForm, RegisterForm, EditForm
from django import forms
from django.core.paginator import Paginator


class IndexView(generic.ListView):
    template_name = 'forum/index.html'
    context_object_name = 'themes'

    def get_queryset(self):
        themes = Theme.objects.order_by('created')
        paginator = Paginator(themes, 10)
        page=self.request.path[1:]
        if page == '':
            page = 1
        try:
            ret_themes = paginator.page(page)
        except:
            ret_themes = ''
        return ret_themes


class DetailsView(generic.DetailView):
    model = Theme
    template_name = 'forum/theme_mess.html'


class LoginView(generic.FormView):
    template_name = 'forum/login.html'
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form):
        username = form.clean()['username']
        password = form.clean()['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            request = self.request
            login(request, user)
            return HttpResponseRedirect(reverse('forum:index'))


class RegisterView(generic.CreateView):
    template_name = 'forum/register.html'
    form_class = RegisterForm
    success_url = '/'

    def form_valid(self, form):
        username = form.clean_username()
        password = form.clean_password2()

        user_f = User.objects.create_user(username=username,
                                          password=password,
                                          )
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return HttpResponseRedirect(reverse('forum:index'))


def add_message(request, pk):
    if request.user != None:
        try:
            message = request.POST['new_message_text']
        except:
            message = ''
        if message != '':
            new_message = Message(theme=Theme.objects.get(pk=pk), text=message, created=timezone.now(), author=request.user)
            new_message.save()
            return HttpResponseRedirect(reverse('forum:theme_mess', args=(pk, )))
    return HttpResponseRedirect(reverse('forum:theme_mess', args=(pk, )))


def add_theme(request):
    if request.user != None:
        try:
            theme = request.POST['new_theme_name']
        except:
            theme = ''
        if theme != '':
            new_theme = Theme(name=theme, created=timezone.now(), author=request.user)
            new_theme.save()
            return HttpResponseRedirect(reverse('forum:theme_mess', args=(new_theme.pk, )))
    return HttpResponseRedirect(reverse('forum:index'))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('forum:index'))


def delete_message(request, tpk, mpk):
    if request.user == Message.objects.filter(pk=mpk)[0].author:
        Message.objects.filter(pk=mpk).delete()
    return HttpResponseRedirect(reverse('forum:theme_mess', args=(tpk, )))


def edit_mess_page(request, tpk, mpk):
    if request.user == Message.objects.filter(pk=mpk)[0].author:
        text = Message.objects.filter(pk=mpk)[0].text
        mess = Message.objects.filter(pk=mpk)[0]
        form = EditForm(request.POST or None, initial={'message': text})
        if request.method == 'POST' and form.is_valid():
            mess.text = form.cleaned_data.get('message')
            mess.save()
            return HttpResponseRedirect(reverse('forum:theme_mess', args=(tpk, )))

        context = {'form': form, 'tpk': tpk, 'mpk': mpk, 'text': text}
        return render(request, 'forum/edit_mess.html', context)
    return HttpResponseRedirect(reverse('forum:theme_mess', args=(tpk, )))

forum/templates/forum/edit_mess.html
{% extends "forum/masterpage.html" %}
{% block content %}

<h1>Edit message</h1>

<form action="" method = 'post' id='edit_mess'>
        {% csrf_token %}
        {{ form.message }}
        <input type = 'submit' name = 'send_new_message' id = 'send_new_message_button' value = 'Send' />
</form>
{% endblock %}

forum/templates/forum/index.html
{% extends "forum/masterpage.html" %}

{% block content %}

{% if themes %}
    <table id='themes'>
        {% for theme in themes %}
            <tr class='theme'>
                <td class='theme_name'><a href="{% url 'forum:theme_mess' theme.pk %}">{{ theme.name }}</a></td><td class='theme_author'><a href="{% url 'forum:theme_mess' theme.pk %}">{{ theme.author }}</a></td><td class='theme_date'><a href="{% url 'forum:theme_mess' theme.pk %}">{{ theme.created }}</a></td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>Here is no themes!</p>
{% endif %}

<span class="step-links">
    {% if themes.has_previous %}
        <a href="{{ themes.previous_page_number }}">&laquo; back</a>
    {% endif %}
    <span class="current"> {{ themes.number }} of {{ themes.paginator.num_pages }} </span>
    {% if themes.has_next %}
        <a href="{{ themes.next_page_number }}">next &raquo;</a>
    {% endif %}
</span>

{% if user.is_authenticated %}
    <form action="{% url 'forum:add_theme' %}" method = 'post' id='create_theme'>
        {% csrf_token %}
        <input type = 'text' name = 'new_theme_name' id = 'new_theme_name_input' maxlength = '100' size = '100' required maxlength='100'/>
        <input type = 'submit' name = 'send_new_theme' id = 'send_new_theme_button' value = 'Create Theme' />
    </form>
{% endif %}


{% endblock %}

forum/templates/forum/login.html
{% extends "forum/masterpage.html" %}

{% block content %}
    <form id='login_form' action="" method = 'post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input id='login_button' type = 'submit' name = 'send_logpass' id = 'send_logpass_button' value = 'Log In' />
    </form>
{% endblock %}

forum/templates/forum/masterpage.html
<!DOCTYPE html>
<html>
<head>
    <title>Forum</title>
</head>
<body>

{% load staticfiles %}
<link rel = 'stylesheet' type = 'text/css' href = '{% static "forum/style.css" %}' />


<div id='content'>
    <div id='header'>
        <div id='home'><a href = '{% url "forum:index" %}'>Home</a></div>

        {% if user.is_authenticated %}
            <div id='hello'>Hello, <b>{{ user.username }}</b>!</div>
            <div id='logout'><a href = '{% url "forum:logout" %}'>Log Out</a></div>
        {% else %}
            <div id='login'><a href = '{% url "forum:login_page" %}'>Log In</a></div>
            <div id='registration'><a href = '{% url "forum:register" %}'>Register</a></div>
        {% endif %}
    </div>

    <div id='forum_content'>
        {% block content %}
        {% endblock %}
    </div>
</div>

</body>
</html>

forum/templates/forum/register.html
{% extends "forum/masterpage.html" %}

{% block content %}
    {% if error_mess %}
        <p class = 'error'>{{ error_mess }}</p>
    {% endif %}

    <form id='register_form' action="" method = 'post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type = 'submit' name = 'send_logpass' id = 'send_logpass_button' value = 'Log In' />
    </form>
{% endblock %}

forum/templates/forum/theme_mess.html
{% extends "forum/masterpage.html" %}

{% block content %}
<h1>{{ theme.name }}</h1>

{% if theme.message_set.all|length == 0 %}
    <h1>There is no message yet :(</h1>
{% endif %}
    <table id='messages'>
    {% for message in theme.message_set.all %}
        <tr>
        <td class='mes_author'><p>{{ message.author }}</p></td><td class='mes_date'><p>{{ message.created }}</p></td><td class='mes_text'><p>{{ message.text }}</p></td>
            {% if message.author == user %}
                <td class='other'><a href='{% url "forum:edit_mess" theme.pk message.pk %}'>Edit</a>
                <a href='{% url "forum:delete_mess" theme.pk message.pk %}'>Delete</a></td>
            {% endif %}
        </tr>
    {% endfor %}
    </table>

{% if user.is_authenticated %}
    <form id='send_mess' action="{% url 'forum:add_message' theme.pk %}" method = 'post'>
        {% csrf_token %}
        <input type = 'text' name = 'new_message_text' id = 'new_message_text_input' maxlength = '1000' size = '100' required />
        <input type = 'submit' name = 'send_new_message' id = 'send_new_message_button' value = 'Send' />
    </form>
{% endif %}
{% endblock %}